<?xml version="1.0" ?>
<migrations>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Document.IsReadOnly</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Document.IsReadOnly</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Document.SetCoordinateSystemCode</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Document.SetCoordinateReferenceSystem</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Document.SetDrawingScale</oldName>
    <newName>Autodesk.Civil.DynamoNodes.CivilDocument.SetScale</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Document.SetSystemVariable</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Document.SetSystemVariable</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.Block</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.Block</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.GetLayouts</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.GetLayouts</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.Name</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.Name</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.TabOrder</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.TabOrder</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.Reorder</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.Reorder</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Layout.SetName</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layout.SetName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.SetName</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.SetName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.SetDescription</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.SetDescription</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.SetExplodable</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.SetExplodable</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.IsAnonymous</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.IsAnonymous</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.IsDynamic</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.IsDynamic</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Block.Explodable</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Block.IsExplodable</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Layer.Lineweight</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layer.Lineweight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Layer.SetColor</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layer.SetColor</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Layer.SetLineweight</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Layer.SetLineweight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.Block</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.SourceBlock</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.BlockPosition</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.BlockLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.ContentType</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.ContentType</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.GetAttributeValueByTag</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.BlockAttributeValueByTag</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.SetAttributeValueByTag</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.SetBlockAttributeValueByTag</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.LeaderPoints</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.ArrowheadLocations</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.Scale</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.OverallScale</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.TextLocation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.TextLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MLeader.LeaderLineCount</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Multileader.LeaderCount</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MText.TextStyle</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.MText.TextStyle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.MText.SetTextStyle</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.MText.SetTextStyle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Object.SetColor</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetColor</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.Contents</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.Contents</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.Height</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.TextHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.IsBackward</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.IsBackward</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.IsUpsideDown</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.IsUpsideDown</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.Obliquing</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.ObliqueAngle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.Position</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Location</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.Rotation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Rotation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetContents</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetContents</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetHeight</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetTextHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetIsBackward</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetBackward</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetIsUpsideDown</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetUpsideDown</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetObliquing</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetObliqueAngle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetPosition</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetRotation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetRotation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetTextStyle</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetTextStyle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.SetWidthFactor</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.SetWidthFactor</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.TextStyle</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.TextStyle</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Text.WidthFactor</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Text.WidthFactor</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline3D.IsClosed</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Curve.IsClosed</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline3D.SetIsClosed</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Curve.SetClosed</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.Elevation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Polyline.Elevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.GlobalWidth</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Polyline.GlobalWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.IsClosed</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Curve.IsClosed</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.SetElevation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Polyline.SetElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.SetGlobalWidth</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Polyline.SetGlobalWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.AutoCAD.Objects.Polyline.SetIsClosed</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Curve.SetClosed</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Alignment.Geometry</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Alignment.PolyCurve</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Alignment.ProfileViews</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Alignment.ProfileViews</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Alignment.SampleLineGroups</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Alignment.SampleLineGroups</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Alignment.SetStartStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Alignment.SetReferencePointStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.CivilObject.GetReferenceInfo</oldName>
    <newName>Autodesk.Civil.DynamoNodes.CivilObject.ReferenceInfo</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.CivilObject.IsReference</oldName>
    <newName>Autodesk.Civil.DynamoNodes.CivilObject.IsReferenceObject</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.Alignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.Alignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.ByPoint</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.ByAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.MaxElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.MaxElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.MinElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.MinElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.Location</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Location</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.EndStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.EndStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.StartStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.StartStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.GetPointAtStationElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.PointAtStationElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.GetStationElevationAtPoint</oldName>
    <newName>Autodesk.Civil.DynamoNodes.ProfileView.StationElevationAtPoint</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.ProfileView.SetLocation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.Geometry</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Geometry</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.LockToStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.IsLockedToStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.Number</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.Number</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.SampleLineGroup</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.SampleLineGroup</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.SectionViews</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.SectionViews</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.SetLockToStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.SetLockedToStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.SetStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.SetStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLine.Station</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLine.Station</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLineGroup.Alignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLineGroup.Alignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SampleLineGroup.SampleLines</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SampleLineGroup.SampleLines</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.GetOffsetElevationAtPoint</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.OffsetElevationAtPoint</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.GetPointAtOffsetElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.PointAtOffsetElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.IsElevationRangeAutomatic</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.IsElevationRangeAutomatic</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.IsOffsetRangeAutomatic</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.IsOffsetRangeAutomatic</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.Location</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Location</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.MaxElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.MaxElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.MinElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.MinElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.OffsetLeft</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.LeftOffset</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.OffsetRight</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.RightOffset</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.SampleLine</oldName>
    <newName>Autodesk.Civil.DynamoNodes.SectionView.SampleLine</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.SectionView.SetLocation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.ByName</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.ByName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.FindShortestNetworkPath</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.ShortestPathBetweenParts</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.GetPipeNetworks</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.GetPipeNetworks</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.Pipes</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.Pipes</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.Structures</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.Structures</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.ReferenceAlignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.ReferenceAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.PipeNetwork.ReferenceSurface</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PipeNetwork.ReferenceSurface</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.AddToProfileView</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.AddToProfileView</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.ApplyRules</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.AddToProfileView</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.Domain</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.Domain</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.Material</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.Material</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.PartDescription</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.PartDescription</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.PartSubType</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.PartSubType</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.PipeNetwork</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.PipeNetwork</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.ProfileViewsDisplayedIn</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.ProfileViewsDisplayedIn</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.ReferenceAlignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.ReferenceAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.ReferenceSurface</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.ReferenceSurface</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.RemoveFromProfileView</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.RemoveFromProfileView</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.SectionsViewsDisplayedIn</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.SectionsViewsDisplayedIn</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.SetReferenceAlignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.SetReferenceAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Part.SetReferenceSurface</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Part.SetReferenceSurface</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.Bearing</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.Bearing</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.CoverStart</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.StartCover</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.CoverEnd</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EndCover</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.CrossSectionalShape</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.CrossSectionalShape</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EndPoint</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EndPoint</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EndOffset</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EndOffset</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EndStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EndStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EndStructure</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EndStructure</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EGLDown</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EnergyGradeLineDown</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.EGLUp</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.EnergyGradeLineUp</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.FlowDirectionMethod</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.FlowDirectionMethod</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.FlowRate</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.FlowRate</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.HGLDown</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.HydraulicGradeLineDown</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.HGLUp</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.HydraulicGradeLineUp</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.InnerDiameterOrWidth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.InnerDiameterOrWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.InnerHeight</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.InnerHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.JunctionLoss</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.JunctionLoss</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.CoverMax</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.MaxCover</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.CoverMin</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.MinCover</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.OuterDiameterOrWidth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.OuterDiameterOrWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.OuterHeight</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.OuterHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.Radius</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.Radius</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.ReturnPeriod</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.ReturnPeriod</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.Slope</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.Slope</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.StartPoint</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.StartPoint</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.StartOffset</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.StartOffset</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.StartStation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.StartStation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.StartStructure</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.StartStructure</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Pipe.ResizeByInnerDimension</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Pipe.Resize</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.AutomaticRimSurfaceAdjustment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.AutomaticSurfaceAdjustment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.BarrelPipeClearance</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.BarrelPipeClearance</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.ControlSumpBy</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.SumpControlMethod</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Cover</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Cover</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.OuterDiameterOrWidth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.OuterDiameterOrWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.FloorThickness</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.FloorThickness</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Frame</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Frame</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.FrameDiameter</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.FrameDiameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.FrameHeight</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.FrameHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Grate</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Grate</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.HeadwallBaseThickness</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.HeadwallBaseThickness</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.HeadwallBaseWidth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.HeadwallBaseWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Height</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Height</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.InnerDiameterOrWidth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.InnerDiameterOrWidth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.InnerLength</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.InnerLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Length</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Length</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Location</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Location</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Offset</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Offset</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.PipeLowestBottomDepth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.DepthToLowestPipeBottom</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.PipeUpperTopDepth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.DepthToUpperPipeTop</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.RimElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.RimElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.RimToSumpHeight</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.RimToSumpHeight</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Rotation</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Rotation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.Station</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.Station</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.SumpDepth</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.SumpDepth</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.SumpElevation</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.SumpElevation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.SurfaceAdjustmentValue</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.SurfaceAdjustmentValue</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.VerticalPipeClearance</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.VerticalPipeClearance</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PipeNetworks.Parts.Structure.ResizeByPipeDepths</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Structure.ResizeByPipeDepths</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.PressureNetwork.Appurtenances</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressureNetwork.Appurtenances</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.PressureNetwork.ByName</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressureNetwork.ByName</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.PressureNetwork.PressurePipes</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressureNetwork.PressurePipes</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.PressureNetwork.Fittings</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressureNetwork.Fittings</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.PressureNetwork.GetPressureNetworks</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressureNetwork.GetPressureNetworks</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.AddToProfileView</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.AddToProfileView</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.Domain</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.Domain</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.PartData</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.PartData</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.PartDescription</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.PartDescription</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.PartType</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.PartType</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.PressureNetwork</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.PressureNetwork</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.ProfileViewsDisplayedIn</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.ProfileViewsDisplayedIn</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.ReferenceAlignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.ReferenceAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.ReferenceSurface</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.ReferenceSurface</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.RemoveFromProfileView</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.RemoveFromProfileView</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.SetPosition</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.SetLocation</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.SetReferenceAlignment</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.SetReferenceAlignment</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.SetReferenceSurface</oldName>
    <newName>Autodesk.Civil.DynamoNodes.PressurePart.SetReferenceSurface</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.PressureNetworks.Parts.PressurePart.Solid</oldName>
    <newName>Autodesk.AutoCAD.DynamoNodes.Object.Geometry</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.AutoRebuild</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.AutomaticRebuild</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.HasSnapshot</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.HasSnapshot</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.IsOutOfDate</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.IsOutOfDate</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.CreateWaterDrop</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.WaterDropPaths</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.IsLocked</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.IsLocked</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.SetAutoRebuild</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.SetAutomaticRebuild</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Camber.Civil.CivilObjects.Surfaces.Surface.SetIsLocked</oldName>
    <newName>Autodesk.Civil.DynamoNodes.Surface.SetLocked</newName>
  </priorNameHint>
</migrations>
